theme: jekyll-theme-minimal
title: Sundar Rajan Muthuraj
description: Seasoned Principal Engineer | Clean Coder | Aspiring CTO
plugins:
  - jekyll-include-cache
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
